version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./index.php:/var/www/html/index.php
    ports:
      - "9000:80"
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "8080:80"
    depends_on:
      - php
